### ISSUE TITLE
是不是少了prettier依赖？

### ISSUE THREAD

**Issue by BearTheMad** [bigTig/react-webpack-ts#10]
执行yarn prettier提示
$ yarn prettier
yarn run v1.22.17
$ prettier --write "**/**.{js,jsx,tsx,ts,less,md,json}" --loglevel warn
'prettier' is not recognized as an internal or external command,
operable program or batch file.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by bigTig** [comment]
`npm install --save-dev --save-exact prettier`
@BearTheMad 项目依赖上没有安装，我在本地vscode安装，你可以安装就好了
