### ISSUE TITLE
增加 iframe

### ISSUE THREAD

**Issue by HoneyJoe** [bigTig/react-webpack-ts#3]
你好，如果想通过iframe，内嵌一个独立的模块 这个应该怎么设计呢？

**Comment by Kevin9505** [comment]
谢谢您的真诚来信，我们会尽快给您回复！

**Comment by bigTig** [comment]
@HoneyJoe 可以举个栗子吗，没太理解你的想法，利用 router 配合 layout 来实现？

**Comment by HoneyJoe** [comment]
抱歉、因为不是搞前端的，我的前端知识仅停留在生疏的jquery阶段，所以描述的不是很清楚。
需求：是搞一个通用的后台模版，可以引用其他项目编译好的前端文件，通过点击菜单动态加载进本项目。想到用iframe是便于模块分离，同时两个独立的项目样式不会受到彼此干扰。
例如：https://github.com/DTStack/Taier/blob/master/README_zh-CN.md 这个项目，我想单独打包编译，通过nginx配置等等 嵌入您开源的这个项目，通过点击左侧菜单的形式，展示该页面。

**Comment by HoneyJoe** [comment]
@bigTig

**Comment by bigTig** [comment]
可参考下 hotfix/iframe  分支，是否符合 @HoneyJoe

**Comment by HoneyJoe** [comment]
好的，我研究一下，感谢 🙏 @bigTig
