### ISSUE TITLE
大佬有没有兴趣在掘金出个教程？

### ISSUE THREAD

**Issue by ruidubai** [bigTig/react-webpack-ts#5]
如题

**Comment by bigTig** [comment]
什么样的教程呀

**Comment by bigTig** [comment]
欢迎 Star⭐

**Comment by ruidubai** [comment]
大佬搭建的比较的好，就是一些环境搭建的文章。大佬搭建的效果和功能比慕课收费的还好，可以出一系列文章

**Comment by bigTig** [comment]
害，掘金大佬太多，不敢献丑，后续会在 Wiki 上逐渐添加 @ruidubai 
喜欢的话可以帮忙推荐一波，给个小 Star 🌟
万般感谢🙏

**Comment by bigTig** [comment]
@ruidubai 有想法可以交流学习😜一般都会在线🧵
